name: lfb_env
channels:
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0
  - altair=5.4.1
  - appnope=0.1.4
  - asttokens=2.4.1
  - attrs=24.2.0
  - aws-c-auth=0.7.31
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.28
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.10
  - aws-c-io=0.14.18
  - aws-c-mqtt=0.10.6
  - aws-c-s3=0.6.6
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.20
  - aws-crt-cpp=0.28.3
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.9.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - blinker=1.8.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.9.24
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cycler=0.12.1
  - debugpy=1.8.6
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.54.1
  - freetype=2.12.1
  - gflags=2.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.7.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=7.2.1
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.28.0
  - ipywidgets=8.1.5
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.10.1
  - libcxx=19.1.1
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.29.0
  - libgoogle-cloud-storage=2.29.0
  - libgrpc=1.65.5
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libparquet=17.0.0
  - libpng=1.6.44
  - libprotobuf=5.27.5
  - libre2-11=2023.09.01
  - libsodium=1.0.20
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxgboost=2.1.1
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=19.1.0
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - munkres=1.1.4
  - narwhals=1.9.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numba=0.60.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=2.0.2
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=0.5.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - protobuf=5.27.5
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.1
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pycparser=2.22
  - pydeck=0.8.0
  - pygments=2.18.0
  - pyparsing=3.1.4
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rich=13.9.2
  - rpds-py=0.20.0
  - scikit-learn=1.4.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.1.0
  - shap=0.42.1
  - six=1.16.0
  - slicer=0.0.7
  - smmap=5.0.0
  - snappy=1.2.1
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - streamlit=1.39.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - tzlocal=5.2
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - validators=0.34.0
  - watchdog=5.0.3
  - wcwidth=0.2.13
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - xgboost=2.1.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - beautifulsoup4==4.12.3
      - filelock==3.16.1
      - gdown==5.2.0
      - soupsieve==2.6
      - streamlit-shap==1.0.2