name: lfb_env
channels:
  - conda-forge
#  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn=1.4.2 
  - streamlit
  - matplotlib
  - seaborn
  - shap=0.42.1
  - xgboost
  - pip
  - pip:
    - streamlit-shap==1.0.2
    - gdown